#!/usr/bin/env python3
"""Rank public repositories and render the "Featured Projects" section of README.md.

Every public, non-fork, non-archived repository gets a score from 0 to 100:

    recency        20  last push, decays linearly to 0 over 540 days
    commits        25  log-scaled, 60+ commits = full marks
    codebase size  15  log-scaled bytes of source code (binaries/zips ignored)
    documentation  25  real README (not a framework template) 12,
                       description 6, topics 4, homepage 3
    community      10  stars and forks, 5 points each (capped)
    license         5  has a license file

Repos in `pinned` are always featured first; repos in `exclude` never appear.
Card text comes from `.github/featured-projects.json` when present, otherwise
from the repository description.

Usage:
    python scripts/featured_projects.py                 # update README.md
    python scripts/featured_projects.py --dry-run       # print ranking only
    python scripts/featured_projects.py --fixture f.json
    python scripts/featured_projects.py --sync-metadata # push descriptions/topics
"""
from __future__ import annotations

import argparse
import base64
import datetime as dt
import json
import math
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / ".github" / "featured-projects.json"
README_PATH = ROOT / "README.md"
START = "<!-- FEATURED-PROJECTS:START -->"
END = "<!-- FEATURED-PROJECTS:END -->"
API = "https://api.github.com"

# Boilerplate READMEs generated by project templates; they don't count as docs.
TEMPLATE_MARKERS = (
    "a new flutter project",
    "this template provides a minimal setup",
    "getting started with create react app",
    "codeigniter rest server with jwt authentication",
)

# name -> (hex colour, simple-icons logo slug or "")
BADGES = {
    "flutter": ("02569B", "flutter"),
    "dart": ("0175C2", "dart"),
    "react": ("20232A", "react"),
    "vite": ("646CFF", "vite"),
    "tailwind css": ("06B6D4", "tailwindcss"),
    "supabase": ("3ECF8E", "supabase"),
    "firebase": ("DD2C00", "firebase"),
    "vercel": ("000000", "vercel"),
    "riverpod": ("0553B1", ""),
    "bloc": ("1E88E5", ""),
    "hive": ("FFB300", ""),
    "codemagic": ("F45E3F", "codemagic"),
    "sqlite": ("003B57", "sqlite"),
    "mysql": ("4479A1", "mysql"),
    "php": ("777BB4", "php"),
    "codeigniter": ("EF4223", "codeigniter"),
    "jwt": ("000000", "jsonwebtokens"),
    "sap": ("0FAAFF", "sap"),
    "node.js": ("339933", "nodedotjs"),
    "express": ("000000", "express"),
    "hapi": ("F28C28", ""),
    "python": ("3776AB", "python"),
    "flask": ("000000", "flask"),
    "fastapi": ("009688", "fastapi"),
    "pytorch": ("EE4C2C", "pytorch"),
    "transformers": ("FFD21E", "huggingface"),
    "machine learning": ("FF6F00", ""),
    "javascript": ("F7DF1E", "javascript"),
    "typescript": ("3178C6", "typescript"),
    "vue": ("4FC08D", "vuedotjs"),
    "html": ("E34F26", "html5"),
    "jupyter notebook": ("F37626", "jupyter"),
    "java": ("ED8B00", "openjdk"),
    "blade": ("FF2D20", "laravel"),
    "c++": ("00599C", "cplusplus"),
}


# --------------------------------------------------------------------------- data
class GitHub:
    def __init__(self, token: str | None):
        self.token = token

    def request(self, method: str, path: str, body: dict | None = None):
        url = path if path.startswith("http") else API + path
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        if self.token:
            req.add_header("Authorization", f"Bearer {self.token}")
        if data is not None:
            req.add_header("Content-Type", "application/json")
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            return (json.loads(raw) if raw else None), resp.headers

    def get(self, path: str):
        return self.request("GET", path)[0]

    def repos(self, owner: str) -> list[dict]:
        out, page = [], 1
        while True:
            batch = self.get(f"/users/{owner}/repos?type=owner&per_page=100&page={page}")
            out += batch
            if len(batch) < 100:
                return out
            page += 1

    def commit_count(self, owner: str, repo: str) -> int:
        try:
            body, headers = self.request("GET", f"/repos/{owner}/{repo}/commits?per_page=1")
        except urllib.error.HTTPError as e:
            if e.code == 409:  # empty repository
                return 0
            raise
        match = re.search(r'[?&]page=(\d+)>; rel="last"', headers.get("Link") or "")
        return int(match.group(1)) if match else len(body or [])

    def languages(self, owner: str, repo: str) -> dict[str, int]:
        return self.get(f"/repos/{owner}/{repo}/languages") or {}

    def code_bytes(self, owner: str, repo: str) -> int:
        return sum(self.languages(owner, repo).values())

    def readme(self, owner: str, repo: str) -> str:
        try:
            body = self.get(f"/repos/{owner}/{repo}/readme")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return ""
            raise
        return base64.b64decode(body.get("content", "")).decode("utf-8", "replace")


class Fixture:
    """Offline data source for tests: {"repos": [...], "commits": {}, "readmes": {}}."""

    def __init__(self, path: str):
        self.data = json.loads(Path(path).read_text())

    def repos(self, owner):
        return self.data["repos"]

    def commit_count(self, owner, repo):
        return self.data.get("commits", {}).get(repo, 0)

    def languages(self, owner, repo):
        return self.data.get("languages", {}).get(repo, {})

    def code_bytes(self, owner, repo):
        return self.data.get("code_bytes", {}).get(repo, 0)

    def readme(self, owner, repo):
        return self.data.get("readmes", {}).get(repo, "")


# ------------------------------------------------------------------------ scoring
def score(repo: dict, commits: int, code_bytes: int, readme: str, now: dt.datetime) -> dict:
    pushed = dt.datetime.fromisoformat(repo["pushed_at"].replace("Z", "+00:00"))
    days = max(0.0, (now - pushed).total_seconds() / 86400)
    lowered = readme.lower()
    real_readme = len(readme.strip()) >= 300 and not any(m in lowered for m in TEMPLATE_MARKERS)

    parts = {
        "recency": 20 * max(0.0, 1 - days / 540),
        "commits": 25 * min(1.0, math.log10(commits + 1) / math.log10(61)),
        # 1 KB of code scores 0, 1 MB scores full marks
        "size": 15 * min(1.0, max(0.0, math.log10(code_bytes + 1) - 3) / 3),
        "docs": (12 if real_readme else 0)
        + (6 if repo.get("description") else 0)
        + (4 if repo.get("topics") else 0)
        + (3 if repo.get("homepage") else 0),
        "community": min(10, 5 * repo.get("stargazers_count", 0) + 5 * repo.get("forks_count", 0)),
        "license": 5 if repo.get("license") else 0,
    }
    parts["total"] = round(sum(parts.values()), 1)
    return parts


def rank(source, config: dict, now: dt.datetime) -> list[dict]:
    owner = config["owner"]
    exclude = {name.lower() for name in config.get("exclude", [])}
    ranked = []
    for repo in source.repos(owner):
        if (
            repo.get("private")
            or repo.get("fork")
            or repo.get("archived")
            or repo.get("size", 0) == 0
            or repo["name"].lower() in exclude
        ):
            continue
        commits = source.commit_count(owner, repo["name"])
        code_bytes = source.code_bytes(owner, repo["name"])
        readme = source.readme(owner, repo["name"])
        ranked.append({"repo": repo, "commits": commits, "score": score(repo, commits, code_bytes, readme, now)})

    pinned = [p.lower() for p in config.get("pinned", [])]

    def key(item):
        name = item["repo"]["name"].lower()
        return (0, pinned.index(name)) if name in pinned else (1, -item["score"]["total"])

    return sorted(ranked, key=key)


# ---------------------------------------------------------------------- rendering
def badge(name: str) -> str:
    colour, logo = BADGES.get(name.lower(), ("30363D", ""))
    label = urllib.parse.quote(name.replace("-", "--").replace("_", "__").replace(" ", "_"))
    logo_part = f"&logo={logo}&logoColor=white" if logo else ""
    return f'<img src="https://img.shields.io/badge/{label}-{colour}?style=flat-square{logo_part}" alt="{name}" />'


def stack_for(item: dict, config: dict) -> list[str]:
    repo = item["repo"]
    custom = config.get("repos", {}).get(repo["name"], {})
    if custom.get("stack"):
        return custom["stack"]
    return [repo["language"]] if repo.get("language") else []


def month(iso: str) -> str:
    return dt.datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%b %Y")


def card(item: dict, config: dict) -> str:
    repo = item["repo"]
    custom = config.get("repos", {}).get(repo["name"], {})
    title = custom.get("title") or repo["name"]
    emoji = custom.get("emoji", "📁")
    text = custom.get("summary") or custom.get("description") or repo.get("description") or ""
    badges = "\n        ".join(badge(s) for s in stack_for(item, config))
    info = f'🕒 Updated {month(repo["pushed_at"])}'
    if item["commits"] >= 10:  # a tiny count undersells a project, so only show a meaningful one
        info += f' · 🔨 {item["commits"]} commits'
    if repo.get("stargazers_count"):
        info += f' · ⭐ {repo["stargazers_count"]}'
    return f"""    <td width="50%" valign="top">
      <h3>{emoji} <a href="{repo["html_url"]}">{title}</a></h3>
      <p>{text}</p>
      <p>
        {badges}
      </p>
      <sub>{info}</sub>
    </td>"""


def render(ranked: list[dict], config: dict, now: dt.datetime) -> str:
    featured = ranked[: config.get("featured_count", 6)]
    # Undescribed repos look unfinished in a table, so only list the ones with a description.
    described = [
        item for item in ranked[len(featured) :]
        if config.get("repos", {}).get(item["repo"]["name"], {}).get("description") or item["repo"].get("description")
    ]
    more = described[: config.get("more_count", 8)]

    rows = []
    for i in range(0, len(featured), 2):
        cells = [card(item, config) for item in featured[i : i + 2]]
        if len(cells) == 1:
            cells.append('    <td width="50%"></td>')
        rows.append("  <tr>\n" + "\n".join(cells) + "\n  </tr>")
    out = ["<table>", *rows, "</table>"]

    if more:
        out += [
            "",
            "<details>",
            "<summary><b>📂 More projects</b></summary>",
            "<br />",
            "",
            "| Project | Description | Stack | Updated |",
            "|---|---|---|---|",
        ]
        for item in more:
            repo = item["repo"]
            custom = config.get("repos", {}).get(repo["name"], {})
            desc = (custom.get("description") or repo.get("description") or "").replace("|", "\\|")
            stack = " · ".join(stack_for(item, config))
            out.append(f'| [{repo["name"]}]({repo["html_url"]}) | {desc} | {stack} | {month(repo["pushed_at"])} |')
        out += ["", "</details>"]

    out += [
        "",
        f'<sub>🤖 Ranked automatically by <a href="scripts/featured_projects.py">activity, code and documentation score</a> · last updated {now:%d %b %Y}</sub>',
    ]
    return "\n".join(out)


def update_readme(section: str) -> bool:
    text = README_PATH.read_text()
    if START not in text or END not in text:
        sys.exit(f"README.md is missing the {START} / {END} markers")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{START}\n{section}\n{END}{tail}"
    if new == text:
        return False
    README_PATH.write_text(new)
    return True


def strip_date(text: str) -> str:
    return re.sub(r"last updated \d{2} \w{3} \d{4}", "", text)


def summary_table(ranked: list[dict], featured_count: int) -> str:
    lines = [
        "| # | Repository | Score | Recency | Commits | Size | Docs | Community | License |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for i, item in enumerate(ranked, 1):
        s = item["score"]
        mark = " ⭐" if i <= featured_count else ""
        lines.append(
            f'| {i} | {item["repo"]["name"]}{mark} | **{s["total"]}** | {s["recency"]:.1f} | {s["commits"]:.1f} '
            f'| {s["size"]:.1f} | {s["docs"]} | {s["community"]} | {s["license"]} |'
        )
    return "\n".join(lines)


# ------------------------------------------------------------------ metadata sync
def sync_metadata(gh: GitHub, config: dict) -> None:
    owner = config["owner"]
    for name, custom in config.get("repos", {}).items():
        patch = {k: custom[k] for k in ("description", "homepage") if custom.get(k)}
        try:
            if patch:
                gh.request("PATCH", f"/repos/{owner}/{name}", patch)
            if custom.get("topics"):
                gh.request("PUT", f"/repos/{owner}/{name}/topics", {"names": custom["topics"]})
            print(f"✔ {name}")
        except urllib.error.HTTPError as e:
            print(f"✘ {name}: HTTP {e.code} {e.reason}")


# --------------------------------------------------------------------------- main
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="print the ranking without touching README.md")
    parser.add_argument("--fixture", help="read repository data from a JSON file instead of the API")
    parser.add_argument("--now", help="ISO timestamp to score against (for reproducible tests)")
    parser.add_argument("--sync-metadata", action="store_true", help="set repo descriptions/topics from the config")
    args = parser.parse_args()

    config = json.loads(CONFIG_PATH.read_text())

    if args.sync_metadata:
        token = os.environ.get("PROFILE_TOKEN")
        if not token:
            sys.exit("PROFILE_TOKEN is required for --sync-metadata")
        sync_metadata(GitHub(token), config)
        return

    now = dt.datetime.fromisoformat(args.now) if args.now else dt.datetime.now(dt.timezone.utc)
    source = Fixture(args.fixture) if args.fixture else GitHub(os.environ.get("GITHUB_TOKEN"))
    ranked = rank(source, config, now)
    table = summary_table(ranked, config.get("featured_count", 6))
    print(table)

    if summary_file := os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(summary_file, "a") as fh:
            fh.write("## Featured project ranking\n\n" + table + "\n")

    if args.dry_run:
        return

    section = render(ranked, config, now)
    current = README_PATH.read_text()
    old_section = current.split(START, 1)[-1].split(END, 1)[0]
    # Only the date changed? Leave README alone so the weekly run doesn't commit noise.
    if strip_date(old_section.strip()) == strip_date(section.strip()):
        print("\nREADME.md unchanged (ranking is the same)")
        return
    print("\nREADME.md updated" if update_readme(section) else "\nREADME.md unchanged")


if __name__ == "__main__":
    main()
