#!/usr/bin/env python3
"""Generate self-hosted GitHub stats cards (light + dark) for the profile README.

Public stat services (github-readme-stats, streak-stats) are rate-limited and
often return broken images, so the cards are rendered here from the GitHub API
and published to the `profile-assets` branch by a workflow.

Outputs in --out (default: dist/):
    stats-light.svg / stats-dark.svg   repos, stars, commits, contributions, streaks
    langs-light.svg / langs-dark.svg   top languages (weighted by code size and repo count)

Usage:
    python scripts/profile_stats.py [--out dist] [--fixture f.json] [--now ISO]
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
from html import escape
from pathlib import Path

from featured_projects import CONFIG_PATH, Fixture, GitHub

# Platform boilerplate generated by Flutter/CRA templates, not code written by hand.
IGNORED_LANGUAGES = {
    "CMake", "C++", "C", "Swift", "Objective-C", "Kotlin", "Ruby", "Batchfile",
    "Shell", "Dockerfile", "Makefile", "Procfile", "Hack", "Smarty",
}

# GitHub linguist colours for the languages that show up in this profile.
LANGUAGE_COLOURS = {
    "Dart": "#00B4AB", "JavaScript": "#F1E05A", "TypeScript": "#3178C6", "PHP": "#4F5D95",
    "Python": "#3572A5", "Vue": "#41B883", "HTML": "#E34C26", "CSS": "#663399",
    "SCSS": "#C6538C", "Java": "#B07219", "Jupyter Notebook": "#DA5B0B", "Blade": "#F7523F",
    "PLpgSQL": "#336790", "TSQL": "#E38C00", "Hack": "#878787",
}

THEMES = {
    "light": {"bg": "#FFFFFF", "border": "#D0D7DE", "title": "#0969DA", "text": "#1F2328",
              "muted": "#656D76", "accent": "#0969DA", "track": "#EAEEF2"},
    "dark": {"bg": "#0D1117", "border": "#30363D", "title": "#58A6FF", "text": "#E6EDF3",
             "muted": "#8D96A0", "accent": "#58A6FF", "track": "#21262D"},
}

CONTRIBUTIONS_QUERY = """
query($login: String!) {
  user(login: $login) {
    contributionsCollection {
      contributionCalendar {
        totalContributions
        weeks { contributionDays { date contributionCount } }
      }
    }
  }
}
"""


# --------------------------------------------------------------------------- data
def contribution_days(source, login: str) -> list[tuple[str, int]]:
    if isinstance(source, Fixture):
        return [tuple(d) for d in source.data.get("calendar", [])]
    body, _ = source.request("POST", "/graphql", {"query": CONTRIBUTIONS_QUERY, "variables": {"login": login}})
    weeks = body["data"]["user"]["contributionsCollection"]["contributionCalendar"]["weeks"]
    return [(d["date"], d["contributionCount"]) for w in weeks for d in w["contributionDays"]]


def streaks(days: list[tuple[str, int]], today: dt.date) -> tuple[int, int]:
    """Return (current, longest) streak of consecutive days with contributions."""
    counts = {dt.date.fromisoformat(d): c for d, c in days}
    longest = run = 0
    for day in sorted(counts):
        run = run + 1 if counts[day] > 0 else 0
        longest = max(longest, run)
    # Today may still be empty early in the day; don't break the streak for that.
    cursor = today if counts.get(today, 0) > 0 else today - dt.timedelta(days=1)
    current = 0
    while counts.get(cursor, 0) > 0:
        current += 1
        cursor -= dt.timedelta(days=1)
    return current, longest


def collect(source, owner: str, now: dt.datetime) -> dict:
    repos = [r for r in source.repos(owner) if not r.get("fork") and not r.get("private")]
    language_bytes: dict[str, int] = {}
    language_repos: dict[str, int] = {}
    commits = 0
    for repo in repos:
        if repo.get("size", 0) == 0:
            continue
        commits += source.commit_count(owner, repo["name"])
        for lang, size in source.languages(owner, repo["name"]).items():
            if lang not in IGNORED_LANGUAGES:
                language_bytes[lang] = language_bytes.get(lang, 0) + size
                language_repos[lang] = language_repos.get(lang, 0) + 1

    # Rank by sqrt(bytes) * sqrt(repo count): one repo with a bundled framework
    # shouldn't outweigh a language used across many projects.
    weights = {lang: math.sqrt(size) * math.sqrt(language_repos[lang]) for lang, size in language_bytes.items()}

    days = contribution_days(source, owner)
    current, longest = streaks(days, now.date())
    return {
        "repos": len(repos),
        "stars": sum(r.get("stargazers_count", 0) for r in repos),
        "since": min((r["created_at"][:4] for r in repos if r.get("created_at")), default=str(now.year)),
        "commits": commits,
        "contributions": sum(c for _, c in days),
        "current_streak": current,
        "longest_streak": longest,
        "languages": sorted(weights.items(), key=lambda kv: -kv[1]),
    }


# ---------------------------------------------------------------------- rendering
FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif"


def frame(width: int, height: int, title: str, body: str, t: dict) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="{escape(title)}">
  <title>{escape(title)}</title>
  <style>
    .title {{ font: 600 18px {FONT}; fill: {t["title"]}; }}
    .label {{ font: 400 14px {FONT}; fill: {t["muted"]}; }}
    .value {{ font: 700 14px {FONT}; fill: {t["text"]}; }}
    .big   {{ font: 700 26px {FONT}; fill: {t["text"]}; }}
    .small {{ font: 400 12px {FONT}; fill: {t["muted"]}; }}
    .fade  {{ opacity: 0; animation: fadein .6s ease-out forwards; }}
    @keyframes fadein {{ to {{ opacity: 1; }} }}
    @media (prefers-reduced-motion: reduce) {{ .fade {{ animation: none; opacity: 1; }} }}
  </style>
  <rect x="0.5" y="0.5" rx="10" width="{width - 1}" height="{height - 1}" fill="{t["bg"]}" stroke="{t["border"]}"/>
  <text x="25" y="36" class="title">{escape(title)}</text>
{body}
</svg>
"""


def stats_svg(s: dict, t: dict) -> str:
    rows = [
        ("Public repositories", f'{s["repos"]:,}'),
        # A handful of stars undersells the profile; show tenure until stars mean something.
        ("Total stars", f'{s["stars"]:,}') if s["stars"] >= 10 else ("On GitHub since", s["since"]),
        ("Commits in public repos", f'{s["commits"]:,}'),
        ("Contributions (last 12 months)", f'{s["contributions"]:,}'),
    ]
    body = []
    for i, (label, value) in enumerate(rows):
        y = 74 + i * 30
        body.append(
            f'  <g class="fade" style="animation-delay:{i * 120}ms">'
            f'<circle cx="31" cy="{y - 5}" r="4" fill="{t["accent"]}"/>'
            f'<text x="45" y="{y}" class="label">{label}</text>'
            f'<text x="330" y="{y}" class="value" text-anchor="end">{value}</text></g>'
        )
    # Streak panel on the right.
    body.append(f'  <line x1="355" y1="52" x2="355" y2="178" stroke="{t["border"]}"/>')
    for i, (label, value) in enumerate([("Current streak", s["current_streak"]), ("Longest streak", s["longest_streak"])]):
        y = 88 + i * 64
        body.append(
            f'  <g class="fade" style="animation-delay:{480 + i * 120}ms">'
            f'<text x="425" y="{y}" class="big" text-anchor="middle">{value}</text>'
            f'<text x="425" y="{y + 20}" class="small" text-anchor="middle">{label} (days)</text></g>'
        )
    return frame(495, 195, "GitHub Stats", "\n".join(body), t)


def langs_svg(s: dict, t: dict, top: int = 8) -> str:
    langs = s["languages"][:top]
    total = sum(size for _, size in langs) or 1
    width, bar_w = 495, 445
    body, x = [], 25.0
    body.append(f'  <clipPath id="bar"><rect x="25" y="54" width="{bar_w}" height="10" rx="5"/></clipPath>')
    body.append(f'  <g clip-path="url(#bar)"><rect x="25" y="54" width="{bar_w}" height="10" fill="{t["track"]}"/>')
    for lang, size in langs:
        w = bar_w * size / total
        body.append(f'    <rect x="{x:.2f}" y="54" width="{w:.2f}" height="10" fill="{LANGUAGE_COLOURS.get(lang, "#8B949E")}"/>')
        x += w
    body.append("  </g>")
    for i, (lang, size) in enumerate(langs):
        col, row = i % 2, i // 2
        cx, cy = 31 + col * 230, 92 + row * 25
        body.append(
            f'  <g class="fade" style="animation-delay:{i * 90}ms">'
            f'<circle cx="{cx}" cy="{cy - 4}" r="5" fill="{LANGUAGE_COLOURS.get(lang, "#8B949E")}"/>'
            f'<text x="{cx + 12}" y="{cy}" class="value">{escape(lang)}</text>'
            f'<text x="{cx + 200}" y="{cy}" class="label" text-anchor="end">{100 * size / total:.1f}%</text></g>'
        )
    height = 92 + ((len(langs) + 1) // 2) * 25
    return frame(width, max(height, 195), "Most Used Languages", "\n".join(body), t)


# --------------------------------------------------------------------------- main
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default="dist", help="output directory")
    parser.add_argument("--fixture", help="read data from a JSON file instead of the API")
    parser.add_argument("--now", help="ISO timestamp to compute streaks against")
    args = parser.parse_args()

    owner = json.loads(CONFIG_PATH.read_text())["owner"]
    now = dt.datetime.fromisoformat(args.now) if args.now else dt.datetime.now(dt.timezone.utc)
    source = Fixture(args.fixture) if args.fixture else GitHub(os.environ.get("GITHUB_TOKEN"))
    stats = collect(source, owner, now)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, theme in THEMES.items():
        (out / f"stats-{name}.svg").write_text(stats_svg(stats, theme))
        (out / f"langs-{name}.svg").write_text(langs_svg(stats, theme))
    print(json.dumps({k: v for k, v in stats.items() if k != "languages"}, indent=2))
    total = sum(w for _, w in stats["languages"][:8]) or 1
    print("top languages:", ", ".join(f"{l} {100 * w / total:.1f}%" for l, w in stats["languages"][:8]))


if __name__ == "__main__":
    main()
